  
        //fire
        $('.container').on('click','.card.fire',function(){
            $('.card.fire').css('background','#fd7d24')
            $('.card-title.fire').css('color','white')
            $('.card-subtitle.fire').css('color','white')
        }); 
        //water
        $('.container').on('click','.card.water',function(){
            $('.card.water').css('background','#1E90FF')
            $('.card-title.water').css('color','white')
            $('.card-subtitle.water').css('color','white')
        });
        //grass
        $('.container').on('click','.card.grass',function(){
            $('.card.grass').css('background','#9bcc50')
            $('.card-title.grass').css('color','white')
            $('.card-subtitle.grass').css('color','white')
        })
        //bug
        $('.container').on('click','.card.bug',function(){
            $('.card.bug').css('background','#526a36')
            $('.card-title.bug').css('color','white')
            $('.card-subtitle.bug').css('color','white')
        })

        //normal
        $('.container').on('click','.card.normal',function(){
            $('.card.normal').css('background','#344345')
            $('.card-title.normal').css('color','white')
            $('.card-subtitle.normal').css('color','white')
        })

        //flying
        $('.container').on('click','[tipos2="flying"]',function(){
            $('[tipos2="flying"]').css('background','#ccc')
        })
        //poison
        $('.container').on('click','.card.poison',function(){
            $('.card.poison').css('background','#b97fc9')
            $('.card-title.poison').css('color','white')
            $('.card-subtitle.poison').css('color','white')
        })
        //electric
        $('.container').on('click','.card.electric',function(){
            $('.card.electric').css('background','#ffbd00')
            $('.card-title.electric').css('color','white')
            $('.card-subtitle.electric').css('color','white')
        })
        //ground
        $('.container').on('click','.card.ground',function(){
            $('.card.ground').css('background','#db5')
            $('.card-title.ground').css('color','white')
            $('.card-subtitle.ground').css('color','white')
        })
        //fairy
        $('.container').on('click','.card.fairy',function(){
            $('.card.fairy').css('background','#e27a9d')
            $('.card-title.fairy').css('color','white')
            $('.card-subtitle.fairy').css('color','white')
        })
        //psychic
        $('.container').on('click','.card.psychic',function(){
            $('.card.psychic').css('background','#dc439d')
            $('.card-title.psychic').css('color','white')
            $('.card-subtitle.psychic').css('color','white')
        })
        //fighting
        $('.container').on('click','.card.fighting',function(){
            $('.card.fighting').css('background','#ea3b3b')
            $('.card-title.fighting').css('color','white')
            $('.card-subtitle.fighting').css('color','white')
        })
        //rock
        $('.container').on('click','.card.rock',function(){
            $('.card.rock').css('background','#a38c21')
            $('.card-title.rock').css('color','white')
            $('.card-subtitle.rock').css('color','white')
        })
        //ghost
        $('.container').on('click','.card.ghost',function(){
            $('.card.ghost').css('background','#7b62a3')
            $('.card-title.ghost').css('color','white')
            $('.card-subtitle.ghost').css('color','white')
        })
        //ice
        $('.container').on('click','.card.ice',function(){
            $('.card.ice').css('background','#51c4e7')
            $('.card-title.ice').css('color','white')
            $('.card-subtitle.ice').css('color','white')
        })
        //dragon
        $('.container').on('click','.card.dragon',function(){
            $('.card.dragon').css('background','#76e')
            $('.card-title.dragon').css('color','white')
            $('.card-subtitle.dragon').css('color','white')
        })
        //dark
        $('.container').on('click','.card.dark',function(){
            $('.card.dark').css('background','#111111')
            $('.card-title.dark').css('color','white')
            $('.card-subtitle.dark').css('color','white')
        })
        //steel 
        $('.container').on('click','.card.steel',function(){
            $('.card.steel').css('background','#6a6a6a')
            $('.card-title.steel').css('color','white')
            $('.card-subtitle.steel').css('color','white')
        })
